name = "workers-airtable-form"
type = "javascript"

account_id = "cf88de07a5c929e0580f1489eb4a399a"
workers_dev = true

[vars]
AIRTABLE_BASE_ID = "appuoorn3chpgSH2b"
AIRTABLE_TABLE_NAME = "Test"
FORM_URL = "https://workers-airtable-form-czg.pages.dev"
