name = "workers-airtable-form"
type = "javascript"

account_id = "dc56444c4c955a1653106ccf997c1067"
workers_dev = true

[vars]
AIRTABLE_BASE_ID = "appuoorn3chpgSH2b"
AIRTABLE_TABLE_NAME = "Test"
FORM_URL = "https://workers-airtable-form-czg.pages.dev"
